Traceback (most recent call last):
  File "main.py", line 181, in <module>
    main(parser.parse_args()) 
  File "main.py", line 105, in main
    train_dataset = SpecMagnaTagATune('trainSpe1', dataset)
  File "/user/home/ee20947/cw/dataload.py", line 85, in __init__
    dataset_path = dataset[dataset_key]["annotations_path"]
KeyError: 'trainSpe1'
