Traceback (most recent call last):
  File "model.py", line 674, in <module>
    main(parser.parse_args()) 
  File "model.py", line 152, in main
    lr_finder.range_test(train_loader, end_lr=10, num_iter=100)
  File "model.py", line 642, in range_test
    outputs = self.model(inputs)
  File "/mnt/storage/software/languages/anaconda/Anaconda3.8.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "model.py", line 257, in forward
    x = F.relu(self.conv0(x))
  File "/mnt/storage/software/languages/anaconda/Anaconda3.8.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/storage/software/languages/anaconda/Anaconda3.8.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/storage/software/languages/anaconda/Anaconda3.8.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
